[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  STRIPE_SECRET_KEY_PROD = "sk_test_51KRJB4Gi5eXNGIkHXQTluQ6BUJBlzFNpgUYXtu0ToOKw0qHAaIGbgC2iixBalnAQYheP4OpX1wmnu1m2fww3J85K003idaWdKI"
  VITE_STRIPE_PUBLIC_KEY_PROD = "pk_test_51KRJB4Gi5eXNGIkHSucqLNxKB6rfUkfLroMBMYWo8E2u56xqXXsX7TLKZbMUT6IFdtTfWpJtgoEi4zQ3CZzrJiEL00aJtBw3Mu"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200
  force = true

[[headers]]
  for = "/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "*"
    Access-Control-Allow-Headers = "*"
    Content-Security-Policy = "default-src 'self'; connect-src 'self' https://*.stripe.com https://*.supabase.co wss://*.supabase.co; script-src 'self' js.stripe.com 'unsafe-inline'; frame-src 'self' js.stripe.com; img-src 'self' data: https:; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com; font-src 'self' https://fonts.gstatic.com;"
    Permissions-Policy = "payment=(self 'https://js.stripe.com'), fullscreen=(self)"