name: Deploy Supabase Functions

on:
  push:
    branches: [ main ]
    paths:
      - 'supabase/functions/**'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
      
      - uses: supabase/setup-cli@v1
        with:
          version: latest
          
      - name: Deploy Functions
        run: |
          supabase functions deploy stripe-payment-webhook --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          supabase functions deploy create-booking-securely --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
          supabase functions deploy validate-discount-code --project-ref ${{ secrets.SUPABASE_PROJECT_REF }}
        env:
          SUPABASE_ACCESS_TOKEN: ${{ secrets.SUPABASE_ACCESS_TOKEN }} 